name: Tests

on:
  push:
    branches-ignore:
      - master


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["2.7", "3.7"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install dependencies
      #   run: python -m pip install --upgrade pip
      #     pip install tox tox-gh-actions

      # - name: Test with tox
      #   run: tox

      - name: add_requirement
        run:
          pip install -r requirements.txt

      - name: tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run:
          python -m unittest discover -s ./tests
