name: Tests

on:
  push:
    branches-ignore:
      - master


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["2.7", "3.7"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install dependencies
      #   run: python -m pip install --upgrade pip
      #     pip install tox tox-gh-actions

      # - name: Test with tox
      #   run: tox

      - name: test_with_python
        env:
          PYTHONPATH: /github/workspace/src
        run:
          python -m unittest discover -s ./tests
